### ISSUE TITLE
cann't encode with osin complete example

### ISSUE THREAD

**Issue by godcong** [ShaleApps/osinredis#1]
gob must register struct before encode

in osin example complete.go
ar.UserData = struct{ Login string }{Login: "test"}
the unamed struct will be error in gob encode

**Comment by andrewhare** [comment]
Registering types for `UserData` is something that needs to be done by the code that's using `osinredis`:

```go
// Put this somewhere like in main() or init()
gob.Register(yourStruct{})
```
